<?php

// $Id: xoops_version.php,v 1.1 2006/06/14 02:56:52 mikhail Exp $
// ------------------------------------------------------------------------ //
// eJournal - Electronic Journal Management System //
// <http://www.xoopscube.org> //
// ------------------------------------------------------------------------ //
// ------------------------------------------------------------------------ //
// Author:   //
// URL: http://www.iut.ac.ir/, http://www.xoopscube.org/ //
// Project: eJournal  //
// ------------------------------------------------------------------------- //
/**
 * @author        Hassan Nasser <irnavash@yahoo.com>
 * @copyright (c) 2004 The eJournal Project - www.iut.ac.ir
 **/
$modversion['name'] = 'HtmlArea';
$modversion['version'] = 3.0;
$modversion['description'] = 'JavaScript WYSYWYG Editor for HTML TextArea Fields';
$modversion['author'] = 'Hassan Nasseri';
$modversion['credits'] = "<a href='http://www.iut.ac.ir/'>IUT</a>";
$modversion['help'] = '';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/htmlarea.png';
$modversion['dirname'] = 'htmlarea';
// Sql file generated by phpMyAdmin (ALL tables have not prefix!)
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = "papers";
// Admin things
//$modversion['hasAdmin'] = 1;
//$modversion['adminindex'] = "admin/admin_index.php";
//$modversion['adminmenu'] = "admin/admin_menu.php";
// Menu -- content in main menu block
$modversion['hasMain'] = 0;
//$modversion['sub'][1]['name'] = _MI_MENU_LIST;
//$modversion['sub'][1]['url'] = "list.php";
//$modversion['sub'][2]['name'] = _MI_MENU_SUBMIT;
//$modversion['sub'][2]['url'] = "submit.php";
//$modversion['sub'][3]['name'] = _MI_MENU_VOTE;
//$modversion['sub'][3]['url'] = "comment.php";
//$modversion['sub'][4]['name'] = _MI_MENU_TRACK;
//$modversion['sub'][4]['url'] = "track.php";
// Comments
$modversion['hasComments'] = 0;
//*$modversion['comments']['pageName'] = 'paper.php';
//*$modversion['comments']['itemName'] = 'sid';
/*
// Module Configs
// $xoopsModuleConfig['list_rows']
$modversion['config'][1]['name'] = 'list_rows';
$modversion['config'][1]['title'] = '_MI_REF_LISTROWS';
$modversion['config'][1]['description'] = '_MI_REF_LISTROWS_DESC';
$modversion['config'][1]['formtype'] = 'textbox';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = '30';
// $xoopsModuleConfig['show_comment']
$modversion['config'][2]['name'] = 'show_comment';
$modversion['config'][2]['title'] = '_MI_REF_SHOWCOMMENT';
$modversion['config'][2]['description'] = '_MI_REF_SHOWCOMMENT_DESC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = '1';
// $xoopsModuleConfig['show_full']
$modversion['config'][3]['name'] = 'show_full';
$modversion['config'][3]['title'] = '_MI_REF_SHOWFULL';
$modversion['config'][3]['description'] = '_MI_REF_SHOWFULL_DESC';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = '1';
// $xoopsModuleConfig['show_name']
$modversion['config'][4]['name'] = 'show_name';
$modversion['config'][4]['title'] = '_MI_REF_SHOWNAME';
$modversion['config'][4]['description'] = '_MI_REF_SHOWNAME_DESC';
$modversion['config'][4]['formtype'] = 'yesno';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = '1';
// $xoopsModuleConfig['edit_file']
$modversion['config'][5]['name'] = 'edit_file';
$modversion['config'][5]['title'] = '_MI_REF_EDITFILE';
$modversion['config'][5]['description'] = '_MI_REF_EDITFILE_DESC';
$modversion['config'][5]['formtype'] = 'yesno';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = '0';
// $xoopsModuleConfig['total_exp']
$modversion['config'][7]['name'] = 'total_exp';
$modversion['config'][7]['title'] = '_MI_REF_TOTEXP';
$modversion['config'][7]['description'] = '_MI_REF_TOTEXP_DESC';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = '45';
// $xoopsModuleConfig['pending_exp']
$modversion['config'][8]['name'] = 'pending_exp';
$modversion['config'][8]['title'] = '_MI_REF_PENDEXP';
$modversion['config'][8]['description'] = '_MI_REF_PENDEXP_DESC';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = '15';
// $xoopsModuleConfig['default_lang']
$modversion['config'][9]['name'] = 'default_lang';
$modversion['config'][9]['title'] = '_MI_REF_DEFLANG';
$modversion['config'][9]['description'] = '_MI_REF_DEFLANG_DESC';
$modversion['config'][9]['formtype'] = 'textbox';
$modversion['config'][9]['valuetype'] = 'string';
$modversion['config'][9]['default'] = 'english';
// $xoopsModuleConfig['paper_langs']
$modversion['config'][10]['name'] = 'paper_langs';
$modversion['config'][10]['title'] = '_MI_REF_PAPLANGS';
$modversion['config'][10]['description'] = '_MI_REF_PAPLANGS_DESC';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'string';
$modversion['config'][10]['default'] = 'english';
// $xoopsModuleConfig['mail_referee']
$modversion['config'][12]['name'] = 'mail_addref';
$modversion['config'][12]['title'] = '_MI_REF_MAILADDREF';
$modversion['config'][12]['description'] = '_MI_REF_MAILADDREF_DESC';
$modversion['config'][12]['formtype'] = 'yesno';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = '1';
// $xoopsModuleConfig['director_email']
$modversion['config'][13]['name'] = 'director_email';
$modversion['config'][13]['title'] = '_MI_REF_DIREMAIL';
$modversion['config'][13]['description'] = '_MI_REF_DIREMAIL_DESC';
$modversion['config'][13]['formtype'] = 'textbox';
$modversion['config'][13]['valuetype'] = 'string';
$modversion['config'][13]['default'] = '';
// $xoopsModuleConfig['director_name']
$modversion['config'][14]['name'] = 'director_name';
$modversion['config'][14]['title'] = '_MI_REF_DIRNAME';
$modversion['config'][14]['description'] = '_MI_REF_DIRNAME_DESC';
$modversion['config'][14]['formtype'] = 'textbox';
$modversion['config'][14]['valuetype'] = 'string';
$modversion['config'][14]['default'] = '';
// $xoopsModuleConfig['upload_dir']
$modversion['config'][9]['name'] = 'upload_dir';
$modversion['config'][9]['title'] = '_MI_REF_UPDIR';
$modversion['config'][9]['description'] = '_MI_REF_UPDIR_DESC';
$modversion['config'][9]['formtype'] = 'textbox';
$modversion['config'][9]['valuetype'] = 'string';
$modversion['config'][9]['default'] = 'modules/referee/upload';
// $xoopsModuleConfig['upload_maxsize']
$modversion['config'][16]['name'] = 'upload_maxsize';
$modversion['config'][16]['title'] = '_MI_REF_UPMAX';
$modversion['config'][16]['description'] = '_MI_REF_UPMAX_DESC';
$modversion['config'][16]['formtype'] = 'textbox';
$modversion['config'][16]['valuetype'] = 'int';
$modversion['config'][16]['default'] = '10';
*/
